#!/bin/bash


if [[ "$OSTYPE" == "linux-gnu" && -n "$command -v pip3" ]]; then
    sudo apt-get install python3-pip
elif [[ "$OSTYPE" == "darwin"* ]]; then
    curl https://bootstrap.pypa.io/get-pip.py | python3

fi



first (){
    pip install numpy
    pip install matplotlib
    pip install scipy
    pip install networkx
    pip install pyDOE
    pip install shapely
    pip install xlrd
    pip install xlsxwriter
}

second (){
pip3 install numpy
    pip3 install matplotlib
    pip3 install scipy
    pip3 install networkx
    pip3 install pyDOE
    pip3 install shapely
    pip3 install xlrd
    pip3 install xlsxwriter
}

first || second